version: 1.0.{build}
image: Visual Studio 2015
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: LR3M9x23pmQNzD3tOSsIUsAGDVHpE32TNU1rrNczPGHMiMYkmURQ2XcIKDi8yeIl
init:
- cmd: 
install:
- cmd: 
before_build:
- ps: nuget restore
build:
  verbosity: minimal